version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install linters
          command: pip install pycodestyle pyflakes
      - run:
          name: pyflakes
          command: pyflakes yledl/*.py
      - run:
          name: Code style check
          # E266 too many leading ‘#’ for block comment
          # W504 line break after binary operator
          command: |
            pycodestyle --ignore=E266,W504 --max-line-length 100 --statistics --count yledl/*.py || true

  test:
    parameters:
        pyversion:
            type: string
    docker:
      - image: cimg/python:<< parameters.pyversion >>
    steps:
      - checkout
      - run:
          name: Install ffmpeg
          command: |
            sudo apt update
            sudo apt install -y ffmpeg
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -e .[test,extra]
            pip install mypy
      - run:
          name: mypy
          command: mypy --disable-error-code=import-untyped yledl/*.py
      - run:
          name: Unit and integration tests
          command: |
            mkdir -p test-results
            pytest tests --junit-xml=test-results/report.xml
      - store_test_results:
          path: test-results
      - run:
          name: Smoke test
          command: yle-dl --help

workflows:
  main:
    jobs:
      - lint
      - test:
          requires:
            - lint
          matrix:
              parameters:
                  pyversion: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
